### ISSUE TITLE
IPv6 Netz anpassen

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#2]
Die IPv6 muss angepasst werden das ist hier noch Nord

**Comment by MTRNord** [comment]
Mir empfohlener Generator für den Prefix: https://www.sixxs.net/tools/grh/ula/

**Comment by DasNordlicht** [comment]
Berlin hat 2001:bf7::/32
Nach Wahlkreisen sollten wir eigentlich 2001:bf7:1::/44 bekommen

**Comment by MTRNord** [comment]
scheint frei zu sein :)

**Comment by DasNordlicht** [comment]
Die ULA Adresse fehlt aber noch 
fd07:96ae:572e::/48

**Comment by MTRNord** [comment]
whoops ehm änder ich

**Comment by MTRNord** [comment]
Geändert

**Comment by MTRNord** [comment]
Neues Problemchen: es muss /64 als prefix sein.
