### ISSUE TITLE
Text Knoten Fertig ist falsch

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#25]
Es wird nicht darauf eingegangen das wir einen Keyserver haben un der Aufsteller soll seinen Key an uns senden, das ist aber so nicht notwendig!

---------- Falscher Text -----------------

Dein Knoten ist nun fertig eingerichtet.

Dies ist der öffentliche Schlüssel deines Freifunk-Knotens. Erst nachdem er auf den Servern des Schleswig-Flensburger's Freifunk-Projektes eingetragen wurde, kann sich dein Knoten mit dem Schleswig-Flensburger Mesh-VPN verbinden. Bitte schicke dazu diesen Schlüssel und den Namen deines Knotens (Tarp-Lede-Test-1043) an keys@ffslfl.net.
# Tarp-Lede-Test-1043
d54f041a3df2e05137ba5b096f1548abb8d0d1a5ad9c3c2129906213d92e6cd7

Dein Knoten startet gerade neu und wird anschließend versuchen, sich mit anderen Freifunkknoten in seiner Nähe zu verbinden. Weitere Informationen zur Freifunk-Community Kreis Schleswig-Flensburg findest du auf unserer Webseite.

Um zu dieser Konfigurationsseite zurückzugelangen, drücke im normalen Betrieb für drei Sekunden den Reset-Button. Das Gerät wird dann im Config Mode neustarten.

Viel Spaß mit deinem Knoten und der Erkundung von Freifunk!

**Comment by MTRNord** [comment]
Das sollte aber schon gefixt sein. Hm ich gucke mal.

**Comment by DasNordlicht** [comment]
Mist falsche Version geflasht
