### ISSUE TITLE
Nach dem ersten reboot durch die installation keine Übertragung zum Keyserver

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#26]
Firmware 0.4.1-1 09.08.2017
Der Haken vei VPN war unverändert gelassen, der Node meldet sich aber nicht beim Keyserver.

**Comment by MTRNord** [comment]
Was ist output von `uci show tunneldigger`  `uci show fastd` und `logread` ?

**Comment by DasNordlicht** [comment]
Mist falsche Version geflasht
