### ISSUE TITLE
Umschalten von fastd nach L2TP geht nicht

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#27]
nach dem Umschalten von Fastd auf L2TP werden keine Tunneldigger Variablen in die Config geschrieben.
[Test1043_fastd.txt](https://github.com/ffslfl/site-slfl/files/1212748/Test1043_fastd.txt)
[Test1043_L2TP.txt](https://github.com/ffslfl/site-slfl/files/1212749/Test1043_L2TP.txt)

**Comment by MTRNord** [comment]
Fehler in der Logik gefunden. Ich räume das auf

**Comment by DasNordlicht** [comment]
Ist der selbe Bug wie #24

**Comment by MTRNord** [comment]
Vermutlich

**Comment by MTRNord** [comment]
Bitte mit 4cbcee1bb97a6a4ed30140fda6ed1def5fcbfbe6 erneut versuchen (neuster commit in tunneldigger branch)

**Comment by DasNordlicht** [comment]
gelöst mit der FW 0.4.1-3
