### ISSUE TITLE
FW wechsel 0.3.0 nach 0.4.1 fehlerhafte Tunneldigger Variablen

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#28]
es bleiben fehlerhafte Reste in den Variablen wenn man von 0.3.0 > 0.4.1 wechselt

tunneldigger.0=broker
tunneldigger.0.address='51.15.57.212:20050'
tunneldigger.0.uuid='SL-FL0001Lede'
tunneldigger.0.interface='l2tp0'
tunneldigger.0.enabled='1'
tunneldigger.0.hook_script='/etc/tunneldigger/tunneldigger.hook'

**Comment by DasNordlicht** [comment]
ein "uci delete tunneldigger.0" bereinigt den Node so das er wieder arbeitet

**Comment by DasNordlicht** [comment]
Es scheint mit der 0.4.1-4 bereinigt zu sein.
Was ist gemacht worden?
Dokumentieren und schließen.

**Comment by MTRNord** [comment]
das fehlende uci commit tunneldigger hinzugefügt
