### ISSUE TITLE
USB Unterstützung 

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#3]
USB bitte mit einbauen damit man lokale Webservices aufsetzen kann. 
Unterstützung mit in die Config aufnehmen so das man dort die entsprechende Index umstellen kann.  Entweder Statistik oder USB 
Erreichbar unter localnode.slfl.net oder ähnliches.

**Comment by MTRNord** [comment]
Hinzugefügt in der tunneldigger Branch aber nicht getestet

**Comment by Nordrunner01** [comment]
Info für USB: [GLUON USB-Support](https://github.com/freifunk-gluon/gluon/wiki/USB-Support)

Eine Wettercamfunktion fände ich spannend : [Webcam mit GLUON](https://github.com/freifunk-gluon/gluon/wiki/Using-an-USB-Webcam-with-Gluon)

**Comment by rubo77** [comment]
Achtung, die Wiki Seite ist für 2016.x

**Comment by Nordrunner01** [comment]
Bekommt man das auf die aktuelle GLUON-Version portiert ?

Und ist so etwas : http://www.netzmafia.de/skripten/hardware/Webcam/

auf entsprechend leistungsfähigen FF-Routern möglich?

**Comment by MTRNord** [comment]
@Nordrunner01 ich meine da gibt es irgendwo ein gluon paket für weiß aber ncht mehr wo. Sollte aber optional meiner meinung nach sein und nicht in der normal firmware (allein schon aus platz gründen)

**Comment by Nordrunner01** [comment]
@MTRNord Jupp, bin ich ganz deiner Meinung. Sollte als Sonderfall, oder SpezialFW behandelt werden.
