### ISSUE TITLE
Node Status Seite meint bei L2TP kein VPN zu haben

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/site-slfl#30]
Der Text zu **Mesh-VPN** ist **_false_** obwohl die Variable tunneldigger.mesh_vpn.enabled='1' gesetzt ist.

**Comment by MTRNord** [comment]
oder gefixt durch ffslfl/slfl-packages#78be56e67c028818bec13bf86659d2740ede5bb7

**Comment by DasNordlicht** [comment]
ist gefixt
